CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE TB_ALUNOS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255),
DATA_NASCIMENTO DATE,
TURMA INT,
NOTA DECIMAL(4,2)
);
SELECT * FROM TB_ALUNOS;
INSERT INTO TB_ALUNOS(NOME,DATA_NASCIMENTO,TURMA,NOTA) VALUES ("EDUARDO","2003-02-23",57,10);
INSERT INTO TB_ALUNOS(NOME,DATA_NASCIMENTO,TURMA,NOTA) VALUES ("JESSICA","1997-12-05",57,10);
INSERT INTO TB_ALUNOS(NOME,DATA_NASCIMENTO,TURMA,NOTA) VALUES ("ANGELA","1996-05-22",57,10);
INSERT INTO TB_ALUNOS(NOME,DATA_NASCIMENTO,TURMA,NOTA) VALUES ("MARIANA","2003-02-28",57,10);
INSERT INTO TB_ALUNOS(NOME,DATA_NASCIMENTO,TURMA,NOTA) VALUES ("MARIO","1995-05-12",57,10);
INSERT INTO TB_ALUNOS(NOME,DATA_NASCIMENTO,TURMA,NOTA) VALUES ("VINICIUS","2003-02-23",57,6.5);
INSERT INTO TB_ALUNOS(NOME,DATA_NASCIMENTO,TURMA,NOTA) VALUES ("CARLA","2001-02-20",57,6.0);
INSERT INTO TB_ALUNOS(NOME,DATA_NASCIMENTO,TURMA,NOTA) VALUES ("DANIEL","2006-02-23",57,5.9);

SELECT ID,NOME,NOTA FROM TB_ALUNOS WHERE NOTA >7;
SELECT ID,NOME,NOTA FROM TB_ALUNOS WHERE NOTA <7;

UPDATE TB_ALUNOS SET NOTA=7
WHERE ID=6;