CREATE DATABASE DB_E_COMMERCE;

USE DB_E_COMMERCE;

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
CATEGORIA VARCHAR(255),
COR VARCHAR(255),
TAMANHO INT(255),
MARCA VARCHAR(255),
VALOR DOUBLE,
PRIMARY KEY(ID)
);

SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_PRODUTOS(CATEGORIA,COR,TAMANHO,MARCA,VALOR) VALUES ("JOGO","BRANCO",43,"JORDAN","1400");
INSERT INTO TB_PRODUTOS(CATEGORIA,COR,TAMANHO,MARCA,VALOR) VALUES ("TREINO","PRETO","39","ADIDAS","1100");
INSERT INTO TB_PRODUTOS(CATEGORIA,COR,TAMANHO,MARCA,VALOR) VALUES ("CASUAL","BRANCO","38","NIKE","480");
INSERT INTO TB_PRODUTOS(CATEGORIA,COR,TAMANHO,MARCA,VALOR) VALUES ("CASUAL","PRETO","37","VANS","399");
INSERT INTO TB_PRODUTOS(CATEGORIA,COR,TAMANHO,MARCA,VALOR) VALUES ("JOGO","AZUL","42","JORDAN","1350");
INSERT INTO TB_PRODUTOS(CATEGORIA,COR,TAMANHO,MARCA,VALOR) VALUES ("TREINO","BRANCO","40","NIKE","380");
INSERT INTO TB_PRODUTOS(CATEGORIA,COR,TAMANHO,MARCA,VALOR) VALUES ("CASUAL","VERDE","41","PUMA","600");
INSERT INTO TB_PRODUTOS(CATEGORIA,COR,TAMANHO,MARCA,VALOR) VALUES ("CASUAL","BRANCO","42","JORDAN","5200");

SELECT * FROM TB_PRODUTOS WHERE VALOR > 500;
SELECT * FROM TB_PRODUTOS WHERE VALOR < 500;

UPDATE TB_PRODUTOS SET COR = "ROSA", VALOR = "900" WHERE ID = 2;
